# permissions for end users to edit appsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appset-editor-role
rules:
- apiGroups:
  - bundle.niravparikh05
  resources:
  - appsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bundle.niravparikh05
  resources:
  - appsets/status
  verbs:
  - get
