# permissions for end users to view appsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appset-viewer-role
rules:
- apiGroups:
  - bundle.niravparikh05
  resources:
  - appsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bundle.niravparikh05
  resources:
  - appsets/status
  verbs:
  - get
